apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: sampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
   metadata:
     labels:
       app: sampleapp
   spec:
     containers:
     - name: nginx-container
       image: nginx:1.7.9
       ports:
       - containerPort: 80
