version: 0.2
phases:
  install:
    commands:
      - echo "Installing Nginx server"
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo "Build started on July 8th"
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo "Configuring nginx"

artifacts:
  files:
    - '**/*'
